[#3624] - add a basic text to tell user if he/she is offline
akvo/akvo-flow pull request #3668
Opened 2020-11-17 08:31 UTC by marvinkome

#### Before the PR (what is the issue or what needed to be done)
Tell user is he/she is online or offline

#### The solution
This is a simple implementation of using navigator.onLine.
It wouldn't work on some older browsers, but we would handle this edge case in future modifications

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/30107382/99365449-98a4de80-28b7-11eb-90da-1a9078ba53f4.png)

#### Reviewer Checklist
* [ ] Added an explanation about the work done
* [ ] Connected the PR and the issue on Zenhub
* [ ] Added a test plan to the issue
* [ ] Updated the copyright header (when relevant)
* [ ] Formatted the code
* [ ] Added a documentation (if relevant)
* [ ] Added some unit tests (if relevant)

2020-11-17 10:20 UTC, iperdomo requested changes
The `onlineStatus` is a *new* API in the browsers. If you're connected to the local office WiFi you'll be *online* but potentially you can't reach the Flow Dashboard. See the comments on the other PR - https://github.com/akvo/akvo-flow/pull/3625#issuecomment-693384279

Some apps reach to an known service (e.g. Google) to know if you're actually online.

> Unfortunately, these events aren't fully reliable. If you need greater reliability, or if the API isn't implemented in the browser, you can use other signals to detect if you are offline including using service workers and responses from XMLHttpRequest.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events

> "online" does not always mean connection to the internet, it can also just mean connection to some network. 

https://caniuse.com/online-status

2020-11-17 14:20 UTC, marvinkome commented
@iperdomo based on this. Do I remove the current navigator.onLine implementation and replace it with a timeout that pings google every X seconds?

2020-11-17 14:52 UTC, iperdomo commented
> @iperdomo based on this. Do I remove the current navigator.onLine implementation and replace it with a timeout that pings google every X seconds?

Yes, I think is a *safer* approach

2020-11-18 04:23 UTC, iperdomo requested changes
Still waiting for the changes

2020-11-18 05:03 UTC, marvinkome commented on Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
> +          }
https://stackoverflow.com/questions/58518098/fetch-request-to-httpswww-google-com-fails-obviously-with-cors#comment103363447_58518361

This explains this line

2020-11-18 05:10 UTC, iperdomo commented on Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
> +          if (res.status !== 204) {
We want to check if the status is 204? `res.status === 204` right?

2020-11-18 05:35 UTC, iperdomo commented on Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
> +          if (res.status !== 204) {
OK, i tested it, then if we know that `res.status` is `0`, we should check for that? `res.status === 0` ?

2020-11-18 05:44 UTC, iperdomo commented on Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
> +          if (res.status !== 204) {
So either check for `res.status === 0` or remove the whole `if` block, since we don't want to check the status

2020-11-18 08:18 UTC, iperdomo approved these changes

2020-11-18 08:19 UTC, iperdomo commented on Dashboard/app/js/lib/components/reusable/OfflineIndicator/index.jsx
> +    return this.state.isOffline && <p>You are offline. Changes {"won't"} be saved</p>;
@marvinkome what about translations of this messages?

2020-11-18 08:20 UTC, merged